### ISSUE TITLE
(Theory) Retro Game Emulator Plugins?

### ISSUE THREAD

**Issue by Degamisu** [valadaptive/ntsc-rs#64] opened 2024-03-15 13:36 UTC
This might be a stretch, but as I played Crash Bandicoot for the PS1, I tried some of the post-processing effects. The results were.. quite unrealistic. I was thinking if possible, some sort of simplified ntsc-rs GFX plugin for game emulators. For example, Blargg's NTSC filter is a composite filter just for the SNES emulators. 

![image](https://github.com/valadaptive/ntsc-rs/assets/149022474/398d81cf-6436-42c7-b00e-0f9094984d4a)
_blargg's NTSC filter on Sonic the Hedghog, GENS_

However, NTSC-rs implementation of this sort of stuff would be really fun to mess around with, and add on to the uses of this app. The simplification would be crucial to this, as people may not know what some of the things mean, and it also might slow the performance of the game if there are too many things

Again, sorry if this is a little difficult if not unreachable at this point!

**Comment by valadaptive** [comment] 2024-03-15 14:56
Going to close this as a duplicate of https://github.com/valadaptive/ntsc-rs/issues/16. I'm not sure exactly what shader format different emulators use, but I'd imagine it's either all GLSL/HLSL-style shader languages, or something bespoke for each different emulator that would require rewriting ntsc-rs a bajillion different times.

**Comment by Degamisu** [comment] 2024-03-15 14:57
Sure thing!

**Closed by valadaptive** 2024-03-15 14:56 UTC

**Comment by fukionline** [comment] 2024-08-25 20:09
Pretty sure this has been done.
https://github.com/LMP88959/NTSC-CRT
It's just that it has to be embedded into emulators instead of RetroArch shader
