### ISSUE TITLE
INSTANT CRASHING on After Effects 2025 using v0.8.1

### ISSUE THREAD

**Issue by haraij** [valadaptive/ntsc-rs#220] opened 2024-10-30 04:19 UTC
**Whenever you add the effect into any layer it will crash once you delete a layer in the timeline.**  

Version - v0.8.1. 
Program - Adobe After Effects 2025 

Note:
I've first noticed this when I tried to add the effect onto an adjustment layer and went to delete a clip in the timeline with the 'delete key' then it crashed. Before the effect was added into a layer in the timeline, it would allow me to delete layers with no problem. Only after adding it to a layer caused After Effects 2025 to crash - **in the version v0.8.1**. This doesn't just happen to specific layers, this happens to any type of layer whether it be a adjustment layer or a solid. Also, I've tried using older versions to see if it would still happen, and yes it did. Some of the older versions would either crash when I delete a layer, or crash as soon as I add the effect onto a layer in the timeline.  Does anyone know a fix? If so, please inform me! If not, please spread awareness on this so it gets fixed.

**Comment by valadaptive** [comment] 2024-10-30 23:30
I can't reproduce this bug in After Effects 2024. When you say "I've tried using older versions", do you mean older versions of After Effects, or older versions of ntsc-rs?

The After Effects part was rewritten in ntsc-rs v0.8.0; do the crashes still occur in v0.7.3?

**Comment by valadaptive** [comment] 2024-10-31 00:25
OK, I can reproduce this with an adjustment layer when there are no other layers beneath it

**Comment by valadaptive** [comment] 2024-11-02 10:40
This has been fixed in v0.9.0.

**Closed by valadaptive** 2024-11-02 10:40 UTC
Labels: bug
