### ISSUE TITLE
Internal data stream error when trying to render interlaced video as interlaced stream (v0.7.2)

### ISSUE THREAD

**Issue by Prankejten** [valadaptive/ntsc-rs#118] opened 2024-06-08 18:58 UTC
If I try to render an interlaced (encoded as interlaced) video in NTSC-RS with the _Use field_ setting on _Interleaved_, and set _Interlaced output_ to _true_ in the render settings, NTSC-RS gives the following error: **Error creating pipeline: Internal data stream error.**

I have tried both NTSC and PAL resolution interlaced videos, but neither of them renders at all.

Probably what causes this is that interlaced videos all get detected as "telecined" by NTSC-RS as far as I have seen and that might mess some stuff up and cause this error. Trying to render a progressive video (both encoded as progressive and detected by NTSC-RS as progressive with the _Interlaced output_ setting will not give any errors.

Pretty funny because I would guess the interleaved mode is there for actual interlaced content.
![annoying issue with ntsc-rs](https://github.com/valadaptive/ntsc-rs/assets/71499525/26aaeb8d-39e3-4184-9cfa-bc50ac04b0ca)

**Comment by valadaptive** [comment] 2024-06-08 19:19
I've tested this with interlaced videos in the past and IIRC it's worked. There might've been some code changes so I'll test it again, but it would be helpful if you shared the video that you're having trouble with. There is a difference between telecined and interlaced videos, and I haven't tested the former.

**Comment by Prankejten** [comment] 2024-06-08 19:28
> There is a difference between telecined and interlaced videos, and I haven't tested the former.

The videos are encoded as an MPEG-2 interlaced stream and they are true interlaced, by telecined I meant NTSC-RS assumes they are telecined. The _Use field_ setting is greyed out when a video that NTSC-RS guessed is telecined is selected and cannot be changed until you open another video, so maybe it was disabled for a reason, but idk.

> but it would be helpful if you shared the video that you're having trouble with.

It's not just a specific video, it seems to be all videos encoded as an interlaced stream, at least with the MPEG-2 codec anyway. Neither NTSC or PAL spec video was rendered though. I have to go now, but I'll do some additional testing to see if maybe only MPEG-2 interlaced streams fail to render.

**Comment by valadaptive** [comment] 2024-06-08 20:20
I've confirmed that ntsc-rs doesn't work with telecined video; this will be fixed in the next release.

[Here's an MPEG-2 interlaced video that ntsc-rs correctly recognizes as interlaced and *not* telecined](https://github.com/valadaptive/ntsc-rs/assets/79560998/f2b1b0d2-7047-44a3-a206-f581b7b4d311). Can you share *any* example of these "MPEG-2 interlaced streams" that are showing up as telecined in ntsc-rs but interlaced when their metadata is inspected with e.g. ffmpeg?

**Comment by Prankejten** [comment] 2024-06-08 22:50
Here's a short clip I recorded with my camera (Sony DCR-SX34E) a while ago, as an example for something that fails to render in NTSC-RS.

[M2U00259.zip](https://github.com/user-attachments/files/15749819/M2U00259.zip)
(sorry for the zip, github doesn't let me upload MPG files directly for some reason)

**Comment by Prankejten** [comment] 2024-06-11 23:22
Hey, I downloaded the new version of NTSC-RS because I saw that my bug was fixed in it, and...
it still throws an error 
![kép](https://github.com/valadaptive/ntsc-rs/assets/71499525/ab595cdc-2404-4031-ba67-de27b9d98432)
Literally have no idea what's going on

Additionally here's the preset I'm trying to use, incase it throws an error over some effect being enabled, or I don't know
[Slightly crappy VHS (Interlaced).json](https://github.com/user-attachments/files/15795641/Slightly.crappy.VHS.Interlaced.json)

**Comment by valadaptive** [comment] 2024-06-11 23:29
I'm not sure either; I'll have to investigate more. I can reproduce the issue with the video you sent, but if I re-encode the video using ffmpeg, it gets properly recognized as interlaced and renders with no issue. It may be a GStreamer bug.

**Comment by alexlnkp** [comment] 2024-06-27 10:42
Can confirm, happens for me too (tried re-encoding as Quicktime and x264
ffprobe for both:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'vid.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.1.100
  Duration: 00:07:48.01, start: 0.000000, bitrate: 739 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x270 [SAR 1:1 DAR 16:9], 604 kb/s, 24 fps, 24 tbr, 12288 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.3.100 libx264
        timecode        : 01:00:00:00
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 129 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74)
      Metadata:
        handler_name    : VideoHandler
        timecode        : 01:00:00:00
```
and
```
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'vid.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf61.1.100
  Duration: 00:07:48.00, start: 0.000000, bitrate: 759 kb/s
  Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x270 [SAR 1:1 DAR 16:9], 624 kb/s, 24 fps, 24 tbr, 12288 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : FFMP
        encoder         : Lavc61.3.100 libx264
        timecode        : 01:00:00:00
  Stream #0:1[0x2]: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 130 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74)
      Metadata:
        handler_name    : VideoHandler
        timecode        : 01:00:00:00
```

the re-encoded versions were made from a `.MOV` video rendered by davinci resolve
OS specs:
```
OS: Arch Linux x86_64
Kernel: Linux 6.9.6-arch1-1
Packages: 1576 (pacman)
Display (GM27-FFS): 1920x1080 @ 165Hz
WM: Hyprland (Wayland)
CPU: 12th Gen Intel(R) Core(TM) i5-12400F (12) @ 4.40 GHz
GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate [Discrete]
Memory: 6.41 GiB / 31.20 GiB (21%)
```

**Comment by valadaptive** [comment] 2024-11-02 10:44
@Prankejten Can you reproduce this with the latest version? I tried again with the video you originally posted, and while it still incorrectly shows up as "telecined", it does render.

@alexlnkp I tracked down one cause of flakiness when loading and rendering videos--the GStreamer plugin for Nvidia decoding seems to have a race condition causing it to sometimes fail. Since you have an RTX 3060, it may have been trying to use it on some media. Try v0.9.0; do you still experience this issue?

**Comment by Prankejten** [comment] 2024-11-02 11:59
> @Prankejten Can you reproduce this with the latest version? I tried again with the video you originally posted, and while it still incorrectly shows up as "telecined", it does render.

Unfortunately, it still throws that error, both with the video I sent and any other videos I recorded with the camcorder. I think you forgot to set the render output to be interlaced, as rendering the video as a progressive stream has always worked, interlaced rendering is what is broken. But I did find a somewhat of a solution to this issue, I deinterlace videos with QTGMC and then render as progressive in ntsc-rs.

**Comment by alexlnkp** [comment] 2024-11-02 22:30
> @alexlnkp I tracked down one cause of flakiness when loading and rendering videos--the GStreamer plugin for Nvidia decoding seems to have a race condition causing it to sometimes fail. Since you have an RTX 3060, it may have been trying to use it on some media. Try v0.9.0; do you still experience this issue?

Just updated! Works like a charm on v0.9.0! :)

**Closed** 2024-12-19 09:02 UTC
Labels: bug
