### ISSUE TITLE
standalone app. its only outputting 1 image instead of the video

### ISSUE THREAD

**Issue by mastergithub3574** [valadaptive/ntsc-rs#197] opened 2024-10-02 08:33 UTC
its only outputting 1 image instead of the video. yah

**Comment by valadaptive** [comment] 2024-10-02 17:33
I can't reproduce this. What video is it? Can you post a screen recording of the issue?

**Comment by mastergithub3574** [comment] 2024-10-02 20:12
yes hello- its 2 multiple videos...and yeah sure i can..i can send the original files too..

https://github.com/user-attachments/assets/89d52341-e26e-4398-984f-b9dd13af3581

it doesnt even work when its rendered.. (this is just a example vid)

**Comment by valadaptive** [comment] 2024-10-02 22:37
Ah, it seems like this is another issue with variable-framerate videos. I'll try to find a solution for that

**Comment by mastergithub3574** [comment] 2024-10-02 22:38
ah ok. tyy :D

**Comment by emribilemir** [comment] 2024-10-04 22:05
same for me!

**Comment by valadaptive** [comment] 2024-10-21 05:45
Closing as a duplicate of #8

**Closed by valadaptive** 2024-10-21 05:45 UTC
Labels: bug

**Comment by mastergithub3574** [comment] 2024-10-21 05:47
...

**Comment by valadaptive** [comment] 2024-10-21 05:51
Not sure why GitHub says "not planned"--this will be fixed in the next version

**Comment by mastergithub3574** [comment] 2024-10-21 05:52
was wondering that too..idek how this a duplicate..anyways ty xx
